<?php

namespace hidev\codeception\tests\unit\goals;

use hidev\codeception\goals\CodeceptionGoal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-22 at 13:00:41.
 */
class CodeceptionGoalTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CodeceptionGoal
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new CodeceptionGoal('codeception', null);
    }

    protected function tearDown()
    {
    }

    public function testObject()
    {
        $this->assertInstanceOf(CodeceptionGoal::class, $this->object);
    }

}
